### ISSUE TITLE
[idea]: integrate channel view remotely from master site to share libs and reduce any non-optional files per channel

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-central#9]
Here is an example on zeronet called ZeroCDN:
https://bit.no.com:43110/1AMh6MG4K59ki1dPXX1PrgzeeqkMmZ1YKm/docs.html

**Comment by haschimoto** [comment]
Tamas says we can inverse the inclusion:

That means there may be nothing but optional files plus some content-json on a channel, and a remote view from inside the master site.

![channel-rendered-inside-master](https://cloud.githubusercontent.com/assets/20817185/21945027/5eab5398-d9d9-11e6-8b5d-2e15b9c2bb14.jpg)


That way all libs needed to render the channel are on the master.

Now the question is, can one upload and update their own channel site from within the master?

**Comment by dnelband** [comment]
Yes, we can update merged sites from the merger. I think it would be best implemented with a user account like we did in zerovoat, in which user can have multiple channels. This would also make moderation easier

**Comment by dnelband** [comment]
Should i start implementing? I think a big change like this is better done soon to prevent future complications

**Comment by star-buck** [comment]
i dont like it to be tied to a useraccount, so if we can avoid that and re-use the current "clone" button that Siyuan has implemented in the FAQ, it would be okay, since currently anyone anonymously can clone a hub and then anyone else can register another users hub (i think we even dont need a zeroid to register in the future, like anyone can submit content on zerobaord without identifiying himself).

lets think about this thouroughly before getting on to a bigger change.

**Comment by haschimoto** [comment]
i dont like it to be tied to a useraccount (especially not zeroid), so if we can avoid that and re-use the current "clone" button that Siyuan has implemented in the FAQ, it would be okay.

Currently anyone anonymously can clone a hub and then anyone else can register another users hub (i think we shouldnt even need a zeroid to register hubs in the future, like anyone can submit content on zeroboard without identifiying himself).

lets think about this thouroughly before getting on to a bigger change.

**Comment by dnelband** [comment]
In order to write / upload content from merger site to merged we need to use this url structure - 'merged-IFS/channel-address/data/userid/data.json' (for example) so user needs a channel address variable in order to be able to upload / edit content

**Comment by haschimoto** [comment]
so is this possible for people to have their "own section" to store content without a zeroid?
just by the generated uniquie userhash id?

**Comment by dnelband** [comment]
to upload item & edit the channel.json for the channel site a user doesnt necessarily need the zeroid but in order to register the channel in master  a zeroid is required. ill try to implement it without but i think we have to use it at the register channel point.

**Comment by dnelband** [comment]
so its possible to use the auth_address instead of the cert_user_id (zeroid) and to connect between channels & users via that attribute, but user still has to be logged in with zeroid to register. 

the system will store the auth_address variable (for example looks like this - 1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp) but in order to sign & publish user content (anything thats in master/data/users i.e anything that goes in the DB i.e registering channel among other things) user must be using zeroid.

**Comment by dnelband** [comment]
to view user area in the central site:
http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/user/
still in QA
